Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{6}
Code: #pragma ACCEL PIPELINE auto{}
Code: #pragma ACCEL TILE FACTOR=auto{8}
Code: #pragma ACCEL PARALLEL FACTOR=auto{