8. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L2.
9. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L3.
10. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L4.
11. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L5.
12. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L6.
13. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L7.
14. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L8.
15. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L9.
16. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L10.
17. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L11.
18. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L12.
19. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L13.
20. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L14.
21. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L15.
22. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L16}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L16.
23. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L17}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L17.
24. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L18}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L18.
25. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L19}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L19.
26. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L20}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L20.
27. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L21}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L21.
28. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L22}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L22.
29. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L23}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L23.
30. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L24}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L24.
31. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L25}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L25.
32. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L26}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L26.
33. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L27}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L27.
34. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L28}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L28.
35. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L29}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L29.
36. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L30}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L30.
37. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L31}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L31.
38. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L32}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L32.
39. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L33}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L33.
40. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L34}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L34.
41. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L35}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L35.
42. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L36}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L36.
43. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L37}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L37.
44. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L38}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L38.
45. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L39}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L39.
46. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L40}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L40.
47. '#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L41}': Automatically parallelize this loop, with a custom FACTOR=__PARA__L41.
#pragma ACCEL kernel

void kernel_doitgen(double A[25][20][30