<<<<<<< HEAD
#pragma ACCEL kernel
=======
Code: #pragma ACCEL PIPELINE auto{}
Error: 
#pragma ACCEL PIPELINE auto{flatten}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto
>>>>>>> aacacb78d0cb9c57b2f479851f61349c1954fe7a
