Code: #pragma ACCEL PIPELINE auto{}
Error: 
#pragma ACCEL PIPELINE auto{flatten}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto