6. `#pragma ACCEL PIPELINE auto{__PIPE__L2}` - Pipeline tag for loop L2.
7. `#pragma ACCEL TILE FACTOR=auto{__TILE__L2}` - Tile tag for loop L2.
8. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}` - Parallel tag for loop L2.
9. `#pragma ACCEL PIPELINE auto{__PIPE__L3}` - Pipeline tag for loop L3.
10. `#pragma ACCEL TILE FACTOR=auto{__TILE__L3}` - Tile tag for loop L3.
11. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}` - Parallel tag for loop L3.
12. `#pragma ACCEL PIPELINE auto{__PIPE__L4}` - Pipeline tag for loop L4.
13. `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}` - Tile tag for loop L4.
14. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}` - Parallel tag for loop L4.
15. `#pragma ACCEL PIPELINE auto{__PIPE__L5}` - Pipeline tag for loop L5.
16. `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}` - Tile tag for loop L5.
17. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}` - Parallel tag for loop L5.
18. `#pragma ACCEL PIPELINE auto{__PIPE__L6}` - Pipeline tag for loop L6.
19. `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}` - Tile tag for loop L6.
20. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}` - Parallel tag for loop L6.
21. `#pragma ACCEL PIPELINE auto{__PIPE__L7}` - Pipeline tag for loop L7.
22. `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}` - Tile tag for loop L7.
23. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}` - Parallel tag for loop L7.
24. `#pragma ACCEL PIPELINE auto{__PIPE__L8}` - Pipeline tag for loop L8.
25. `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}` - Tile tag for loop L8.
26. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}` - Parallel tag for loop L8.
27. `#pragma ACCEL PIPELINE auto{__PIPE__L9}` - Pipeline tag for loop L9.
28. `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}` - Tile tag for loop L9.
29. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}` - Parallel tag for loop L9.
30. `#pragma ACCEL PIPELINE auto{__PIPE__L10}` - Pipeline tag for loop L10.
31. `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}` - Tile tag for loop L10.
32. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}` - Parallel tag for loop L10.
33. `#pragma ACCEL PIPELINE auto{__PIPE__L11}` - Pipeline tag for loop L11.
34. `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}` - Tile tag for loop L11.
35. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}` - Parallel tag for loop L11.
36. `#pragma ACCEL PIPELINE auto{__PIPE__L12}` - Pipeline tag for loop L12.
37. `#pragma ACCEL TILE FACTOR=auto{__TILE__L12}` - Tile tag for loop L12.
38. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}` - Parallel tag for loop L12.
39. `#pragma ACCEL PIPELINE auto{__PIPE__L13}` - Pipeline tag for loop L13.
40. `#pragma ACCEL TILE FACTOR=auto{__TILE__L13}` - Tile tag for loop L13.
41. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}` - Parallel tag for loop L13.
42. `#pragma ACCEL PIPELINE auto{__PIPE__L14}` - Pipeline tag for loop L14.
43. `#pragma ACCEL TILE FACTOR=auto{__TILE__L14}` - Tile tag for loop L14.
44. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}` - Parallel tag for loop L14.
45. `#pragma ACCEL PIPELINE auto{__PIPE__L15}` - Pipeline tag for loop L15.
46. `#pragma ACCEL TILE FACTOR=auto{__TILE__L15}` - Tile tag for loop L15.
47. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}` - Parallel tag for loop L15.
48. `#pragma ACCEL PIPELINE auto{__PIPE__L16}` - Pipeline tag for loop L16.
49. `#pragma ACCEL TILE FACTOR=auto{__TILE__L16}` - Tile tag for loop L16.
50. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L16}` - Parallel tag for loop L16.
51. `#pragma ACCEL PIPELINE auto{__PIPE__L17}` - Pipeline tag for loop L17.
52. `#pragma ACCEL TILE FACTOR=auto{__TILE__L17}` - Tile tag for loop L17.
53. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L17}` - Parallel tag for loop L17.
54. `#pragma ACCEL PIPELINE auto{__PIPE__L18}` - Pipeline tag for loop L18.
55. `#pragma ACCEL TILE FACTOR=auto{__TILE__L18}` - Tile tag for loop L18.
56. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L18}` - Parallel tag for loop L18.
57. `#pragma ACCEL PIPELINE auto{__PIPE__L19}` - Pipeline tag for loop L19.
58. `#pragma ACCEL TILE FACTOR=auto{__TILE__L19}` - Tile tag for loop L19.
59. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L19}` - Parallel tag for loop L19.
60. `#pragma ACCEL PIPELINE auto{__PIPE__L20}` - Pipeline tag for loop L20.
61. `#pragma ACCEL TILE FACTOR=auto{__TILE__L20}` - Tile tag for loop L20.
62. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L20}` - Parallel tag for loop L20.
63. `#pragma ACCEL PIPELINE auto{__PIPE__L21}` - Pipeline tag for loop L21.
64. `#pragma ACCEL TILE FACTOR=auto{__TILE__L21}` - Tile tag for loop L2