- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}`: Execute loop iterations concurrently, using __PARA__L2 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L2}`: Automatically pipeline loop with pipeline auto{__PIPE__L2}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L2}`: Tile the inner loop with tile factor auto{__TILE__L2}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}`: Execute loop iterations concurrently, using __PARA__L3 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L3}`: Automatically pipeline loop with pipeline auto{__PIPE__L3}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L3}`: Tile the inner loop with tile factor auto{__TILE__L3}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}`: Execute loop iterations concurrently, using __PARA__L4 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L4}`: Automatically pipeline loop with pipeline auto{__PIPE__L4}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}`: Tile the inner loop with tile factor auto{__TILE__L4}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}`: Execute loop iterations concurrently, using __PARA__L5 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L5}`: Automatically pipeline loop with pipeline auto{__PIPE__L5}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}`: Tile the inner loop with tile factor auto{__TILE__L5}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}`: Execute loop iterations concurrently, using __PARA__L6 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L6}`: Automatically pipeline loop with pipeline auto{__PIPE__L6}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}`: Tile the inner loop with tile factor auto{__TILE__L6}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}`: Execute loop iterations concurrently, using __PARA__L7 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L7}`: Automatically pipeline loop with pipeline auto{__PIPE__L7}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}`: Tile the inner loop with tile factor auto{__TILE__L7}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}`: Execute loop iterations concurrently, using __PARA__L8 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L8}`: Automatically pipeline loop with pipeline auto{__PIPE__L8}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}`: Tile the inner loop with tile factor auto{__TILE__L8}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}`: Execute loop iterations concurrently, using __PARA__L9 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L9}`: Automatically pipeline loop with pipeline auto{__PIPE__L9}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}`: Tile the inner loop with tile factor auto{__TILE__L9}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}`: Execute loop iterations concurrently, using __PARA__L10 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L10}`: Automatically pipeline loop with pipeline auto{__PIPE__L10}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}`: Tile the inner loop with tile factor auto{__TILE__L10}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}`: Execute loop iterations concurrently, using __PARA__L11 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L11}`: Automatically pipeline loop with pipeline auto{__PIPE__L11}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}`: Tile the inner loop with tile factor auto{__TILE__L11}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}`: Execute loop iterations concurrently, using __PARA__L12 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L12}`: Automatically pipeline loop with pipeline auto{__PIPE__L12}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L12}`: Tile the inner loop with tile factor auto{__TILE__L12}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}`: Execute loop iterations concurrently, using __PARA__L13 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L13}`: Automatically pipeline loop with pipeline auto{__PIPE__L13}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L13}`: Tile the inner loop with tile factor auto{__TILE__L13}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}`: Execute loop iterations concurrently, using __PARA__L14 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L14}`: Automatically pipeline loop with pipeline auto{__PIPE__L14}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L14}`: Tile the inner loop with tile factor auto{__TILE__L14}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}`: Execute loop iterations concurrently, using __PARA__L15 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L15}`: Automatically pipeline loop with pipeline auto{__PIPE__L15}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L15}`: Tile the inner loop with tile factor auto{__TILE__L15}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L16}`: Execute loop iterations concurrently, using __PARA__L16 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L16}`: Automatically pipeline loop with pipeline auto{__PIPE__L16}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L16}`: Tile the inner loop with tile factor auto{__TILE__L16}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L17}`: Execute loop iterations concurrently, using __PARA__L17 as the parallel factor. 
- `#pragma ACCEL PIPELINE auto{__PIPE__L17}`: Automatically pipeline loop with pipeline auto{__PIPE__L17}.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L17}`: Tile the inner loop with tile factor auto{__TILE__L17}.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L18}`: Execute loop iterations concurrent