- `#pragma ACCEL PARALLEL FACTOR=auto{16}`: The parallelization factor of this parallelized loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}`: The parallelization factor of this parallelized loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}`: The parallelization factor of this parallelized loop.