#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{4}
#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{4}
#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{2}
#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{4}
#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{1}
#pragma ACCEL PIPELINE auto{}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{2}
#pragma ACCEL PIPELINE auto{off}
  
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{4}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{}
#pragma ACCEL TILE FACTOR=auto{1}
  
#pragma ACCEL PARALLEL FACTOR=auto{4}
#pragma ACCEL PIPELINE auto{}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off}
#pragma ACCEL PIPELINE auto{off