- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Parallelize this loop with a parallelization factor of 1
- `#pragma ACCEL PARALLEL FACTOR=auto{8}`: Parallelize this loop with a parallelization factor of 8
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Parallelize this loop with a parallelization factor of 1