#pragma ACCEL kernel stencil


#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{8}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{8}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER TILE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAMETER PIPELINE_FACTOR=auto{1}

#pragma ACCEL PARAME