Code: #pragma ACCEL PIPELINE auto{off}
1. #pragma ACCEL PIPELINE auto{off}
2. #pragma ACCEL PIPELINE auto{off}
3. #pragma ACCEL PIPELINE auto{off}
4. #pragma ACCEL PIPELINE auto{off}
5. #pragma ACCEL PIPELINE auto{off}
6. #pragma ACCEL PIPELINE auto{off}
7. #pragma ACCEL PIPELINE auto{off}
8. #pragma ACCEL PIPELINE auto{off}
9. #pragma ACCEL PIPELINE auto{off}
10. #pragma ACCEL PIPELINE auto{off}
11. #pragma ACCEL PIPELINE auto{off}
12. #pragma ACCEL PIPELINE auto{off}
13. #pragma ACCEL PIPELINE auto{off}
14. #pragma ACCEL PIPELINE auto{off}
15. #pragma ACCEL PIPELINE auto{off}
16. #pragma ACCEL PIPELINE auto{off}
17. #pragma ACCEL PIPELINE auto{off}
18. #pragma ACCEL PIPELINE auto{off}
19. #pragma ACCEL PIPELINE auto{off}
20. #pragma ACCEL PIPELINE auto{off}
21. #pragma ACCEL PIPELINE auto{off}
22. #pragma ACCEL PIPELINE auto{off}
23. #pragma ACCEL PIPELINE auto{off}
24. #pragma ACCEL PIPELINE auto{off}
25. #pragma ACCEL PIPELINE auto{off}
26. #pragma ACCEL PIPELINE auto{off}
27. #pragma ACCEL PIPELINE auto{off}
28. #pragma ACCEL PIPELINE auto{off}
29. #pragma ACCEL PIPELINE auto{off}
30. #pragma ACCEL PIPELINE auto{off}
31. #pragma ACCEL PIPELINE auto{off}
32. #pragma ACCEL PIPELINE auto{off}
33. #pragma ACCEL PIPELINE auto{off}
34. #pragma ACCEL PIPELINE auto{off}
35. #pragma ACCEL PIPELINE auto{off}
36. #pragma ACCEL PIPELINE auto{off}
37. #pragma ACCEL PIPELINE auto{off}
38. #pragma ACCEL PIPELINE auto{off}
39. #pragma ACCEL PIPELINE auto{off}
40. #pragma ACCEL PIPELINE auto{off}
41. #pragma ACCEL PIPELINE auto{off}
42. #pragma ACCEL PIPELINE auto{off}
43. #pragma ACCEL PIPELINE auto{off}
44. #pragma ACCEL PIPELINE auto{off}
45. #pragma ACCEL PIPELINE auto{off}
46. #pragma ACCEL PIPELINE auto{off}
47. #pragma ACCEL PIPELINE auto{off}
48. #pragma ACCEL PIPELINE auto{off}
49. #pragma ACCEL PIPELINE auto{off}
50. #pragma ACCEL PIPELINE auto{off}
51. #pragma ACCEL PIPELINE auto{off}
52. #pragma ACCEL PIPELINE auto{off}
53. #pragma ACCEL PIPELINE auto{off}
54. #pragma ACCEL PIPELINE auto{off}
55. #pragma ACCEL PIPELINE auto{off}
56. #pragma ACCEL PIPELINE auto{off}
57. #pragma ACCEL PIPELINE auto{off}
58. #pragma ACCEL PIPELINE auto{off}
59. #pragma ACCEL PIPELINE auto{off}
60. #pragma ACCEL PIPELINE auto