5. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L1}` - Set automatic parallelization factor for loop `L1` to automatic{__PARA__L1}.
6. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}` - Set automatic parallelization factor for loop `L2` to automatic{__PARA__L2}.
7. `#pragma ACCEL PIPELINE auto{__PIPE__L2}` - Set automatic pipeline description for loop `L2` to auto{__PIPE__L2}.
8. `#pragma ACCEL TILE FACTOR=auto{__TILE__L2}` - Set automatic tiling description for loop `L2` to auto{__TILE__L2}.
9. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}` - Set automatic parallelization factor for loop `L3` to automatic{__PARA__L3}.
10. `#pragma ACCEL PIPELINE auto{__PIPE__L3}` - Set automatic pipeline description for loop `L3` to auto{__PIPE__L3}.
11. `#pragma ACCEL TILE FACTOR=auto{__TILE__L3}` - Set automatic tiling description for loop `L3` to auto{__TILE__L3}.
12. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}` - Set automatic parallelization factor for loop `L4` to automatic{__PARA__L4}.
13. `#pragma ACCEL PIPELINE auto{__PIPE__L4}` - Set automatic pipeline description for loop `L4` to auto{__PIPE__L4}.
14. `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}` - Set automatic tiling description for loop `L4` to auto{__TILE__L4}.
15. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}` - Set automatic parallelization factor for loop `L5` to automatic{__PARA__L5}.
16. `#pragma ACCEL PIPELINE auto{__PIPE__L5}` - Set automatic pipeline description for loop `L5` to auto{__PIPE__L5}.
17. `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}` - Set automatic tiling description for loop `L5` to auto{__TILE__L5}.
18. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}` - Set automatic parallelization factor for loop `L6` to automatic{__PARA__L6}.
19. `#pragma ACCEL PIPELINE auto{__PIPE__L6}` - Set automatic pipeline description for loop `L6` to auto{__PIPE__L6}.
20. `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}` - Set automatic tiling description for loop `L6` to auto{__TILE__L6}.
21. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}` - Set automatic parallelization factor for loop `L7` to automatic{__PARA__L7}.
22. `#pragma ACCEL PIPELINE auto{__PIPE__L7}` - Set automatic pipeline description for loop `L7` to auto{__PIPE__L7}.
23. `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}` - Set automatic tiling description for loop `L7` to auto{__TILE__L7}.
24. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}` - Set automatic parallelization factor for loop `L8` to automatic{__PARA__L8}.
25. `#pragma ACCEL PIPELINE auto{__PIPE__L8}` - Set automatic pipeline description for loop `L8` to auto{__PIPE__L8}.
26. `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}` - Set automatic tiling description for loop `L8` to auto{__TILE__L8}.
27. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}` - Set automatic parallelization factor for loop `L9` to automatic{__PARA__L9}.
28. `#pragma ACCEL PIPELINE auto{__PIPE__L9}` - Set automatic pipeline description for loop `L9` to auto{__PIPE__L9}.
29. `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}` - Set automatic tiling description for loop `L9` to auto{__TILE__L9}.
30. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}` - Set automatic parallelization factor for loop `L10` to automatic{__PARA__L10}.
31. `#pragma ACCEL PIPELINE auto{__PIPE__L10}` - Set automatic pipeline description for loop `L10` to auto{__PIPE__L10}.
32. `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}` - Set automatic tiling description for loop `L10` to auto{__TILE__L10}.
33. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}` - Set automatic parallelization factor for loop `L11` to automatic{__PARA__L11}.
34. `#pragma ACCEL PIPELINE auto{__PIPE__L11}` - Set automatic pipeline description for loop `L11` to auto{__PIPE__L11}.
35. `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}` - Set automatic tiling description for loop `L11` to auto{__TILE__L11}.
36. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}` - Set automatic parallelization factor for loop `L12` to automatic{__PARA__L12}.
37. `#pragma ACCEL PIPELINE auto{__PIPE__L12}` - Set automatic pipeline description for loop `L12` to auto{__PIPE__L12}.
38. `#pragma ACCEL TILE FACTOR=auto{__TILE__L12}` - Set automatic tiling description for loop `L12` to auto{__TILE__L12}.
39. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}` - Set automatic parallelization factor for loop `L13` to automatic{__PARA__L13}.
40. `#pragma ACCEL PIPELINE auto{__PIPE__L13}` - Set automatic pipeline description for loop `L13` to auto{__PIPE__L13}.
41. `#pragma ACCEL TILE FACTOR=auto{__TILE__L13}` - Set automatic tiling description for loop `L13` to auto{__TILE__L13}.
42. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}` - Set automatic parallelization factor for loop `L14` to automatic{__PARA__L14}.
43. `#pragma ACCEL PIPELINE auto{__PIPE__L14}` - Set automatic pipeline description for loop `L14` to auto{__PIPE__L14}.
44. `#pragma ACCEL TILE FACTOR=auto{__TILE__L14}` - Set automatic tiling description for loop `L14` to auto{__TILE__L14}.
45. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}` - Set automatic parallelization factor for loop `L15` to automatic{__PARA__L15}.
46. `#pragma ACCEL PIPELINE auto{__PIPE__L15}` - Set automatic pipeline description for loop `L15` to auto{__PIPE__L15}.
47. `#pragma ACCEL TILE FACTOR=auto{__TILE__L15}` - Set automatic tiling description for loop `L15` to auto{__TILE__L15}.
48.