5. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L1}` - Replace default parallel factor with user provided value of auto{1} for L1 for optimization in hardware acceleration.
6. `#pragma ACCEL PIPELINE auto{__PIPE__L1}` - Replace default pipeline auto{off} with user provided value of auto{__PIPE__L1} for L1 for optimization in hardware acceleration.
7. `#pragma ACCEL TILE FACTOR=auto{__TILE__L1}` - Replace default tile auto{1} with user provided value of auto{__TILE__L1} for L1 for optimization in hardware acceleration.
8. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}` - Replace default parallel factor with user provided value of auto{__PARA__L2} for L2 for optimization in hardware acceleration.
9. `#pragma ACCEL PIPELINE auto{__PIPE__L2}` - Replace default pipeline auto{__PIPE__L2} with user provided value of auto{__PIPE__L2} for L2 for optimization in hardware acceleration.
10. `#pragma ACCEL TILE FACTOR=auto{__TILE__L2}` - Replace default tile auto{__TILE__L2} with user provided value of auto{__TILE__L2} for L2 for optimization in hardware acceleration.
11. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}` - Replace default parallel factor with user provided value of auto{__PARA__L3} for L3 for optimization in hardware acceleration.
12. `#pragma ACCEL PIPELINE auto{__PIPE__L3}` - Replace default pipeline auto{__PIPE__L3} with user provided value of auto{__PIPE__L3} for L3 for optimization in hardware acceleration.
13. `#pragma ACCEL TILE FACTOR=auto{__TILE__L3}` - Replace default tile auto{__TILE__L3} with user provided value of auto{__TILE__L3} for L3 for optimization in hardware acceleration.
14. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}` - Replace default parallel factor with user provided value of auto{__PARA__L4} for L4 for optimization in hardware acceleration.
15. `#pragma ACCEL PIPELINE auto{__PIPE__L4}` - Replace default pipeline auto{__PIPE__L4} with user provided value of auto{__PIPE__L4} for L4 for optimization in hardware acceleration.
16. `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}` - Replace default tile auto{__TILE__L4} with user provided value of auto{__TILE__L4} for L4 for optimization in hardware acceleration.
17. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}` - Replace default parallel factor with user provided value of auto{__PARA__L5} for L5 for optimization in hardware acceleration.
18. `#pragma ACCEL PIPELINE auto{__PIPE__L5}` - Replace default pipeline auto{__PIPE__L5} with user provided value of auto{__PIPE__L5} for L5 for optimization in hardware acceleration.
19. `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}` - Replace default tile auto{__TILE__L5} with user provided value of auto{__TILE__L5} for L5 for optimization in hardware acceleration.
20. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}` - Replace default parallel factor with user provided value of auto{__PARA__L6} for L6 for optimization in hardware acceleration.
21. `#pragma ACCEL PIPELINE auto{__PIPE__L6}` - Replace default pipeline auto{__PIPE__L6} with user provided value of auto{__PIPE__L6} for L6 for optimization in hardware acceleration.
22. `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}` - Replace default tile auto{__TILE__L6} with user provided value of auto{__TILE__L6} for L6 for optimization in hardware acceleration.
23. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}` - Replace default parallel factor with user provided value of auto{__PARA__L7} for L7 for optimization in hardware acceleration.
24. `#pragma ACCEL PIPELINE auto{__PIPE__L7}` - Replace default pipeline auto{__PIPE__L7} with user provided value of auto{__PIPE__L7} for L7 for optimization in hardware acceleration.
25. `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}` - Replace default tile auto{__TILE__L7} with user provided value of auto{__TILE__L7} for L7 for optimization in hardware acceleration.
26. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}` - Replace default parallel factor with user provided value of auto{__PARA__L8} for L8 for optimization in hardware acceleration.
27. `#pragma ACCEL PIPELINE auto{__PIPE__L8}` - Replace default pipeline auto{__PIPE__L8} with user provided value of auto{__PIPE__L8} for L8 for optimization in hardware acceleration.
28. `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}` - Replace default tile auto{__TILE__L8} with user provided value of auto{__TILE__L8} for L8 for optimization in hardware acceleration.
29. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}` - Replace default parallel factor with user provided value of auto{__PARA__L9} for L9 for optimization in hardware acceleration.
30. `#pragma ACCEL PIPELINE auto{__PIPE__L9}` - Replace default pipeline auto{__PIPE__L9} with user provided value of auto{__PIPE__L9} for L9 for optimization in hardware acceleration.
31. `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}` - Replace default tile auto{__TILE__L9} with user provided value of auto{__TILE__L9} for L9 for optimization in hardware acceleration.
32. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}` - Replace default parallel factor with user provided value of auto{__PARA__L10} for L10 for optimization in hardware acceleration.
33. `#pragma ACCEL PIPELINE auto{__PIPE__L10}` - Replace default pipeline auto{__PIPE__L10} with user provided value of auto{__PIPE__L10} for L10 for optimization in hardware acceleration.
34. `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}` - Replace default tile auto{__TILE__L10} with user provided value of auto{__TILE__L10} for L10 for optimization in hardware acceleration.
35. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}` - Replace default parallel factor with user provided value of auto{__PARA__L11} for L11 for optimization in hardware acceleration.
36. `#pragma ACCEL PIPELINE auto{__PIPE__L11}` - Replace default pipeline auto{__PIPE__L11} with user provided value of auto{__PIPE__L11} for L11 for optimization in hardware acceleration.
37. `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}` - Replace default tile auto{__TILE__L11} with user provided value of auto{__TILE__L11} for L11 for optimization in hardware acceleration.
38. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}` - Replace default parallel factor with user provided value of auto{__PARA__L12} for L12 for optimization in hardware acceleration.
39. `#pragma ACCEL PIPELINE auto{__PIPE__L12}` - Replace default pipeline auto{__PIPE__L12} with user provided value of auto{__PIPE__L12} for L12 for optimization in hardware acceleration.
40. `#pragma ACCEL TILE FA