9. `#pragma ACCEL PIPELINE auto{__PIPE__L2}`: Use the automatic pipeline settings for this loop.
10. `#pragma ACCEL TILE FACTOR=auto{__TILE__L2}`: Use the automatic tile settings for this loop.
11. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L2}`: Use the automatic parallel settings for this loop.
12. `#pragma ACCEL PIPELINE auto{__PIPE__L3}`: Use the automatic pipeline settings for this loop.
13. `#pragma ACCEL TILE FACTOR=auto{__TILE__L3}`: Use the automatic tile settings for this loop.
14. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L3}`: Use the automatic parallel settings for this loop.
15. `#pragma ACCEL PIPELINE auto{__PIPE__L4}`: Use the automatic pipeline settings for this loop.
16. `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}`: Use the automatic tile settings for this loop.
17. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}`: Use the automatic parallel settings for this loop.
18. `#pragma ACCEL PIPELINE auto{__PIPE__L5}`: Use the automatic pipeline settings for this loop.
19. `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}`: Use the automatic tile settings for this loop.
20. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}`: Use the automatic parallel settings for this loop.
21. `#pragma ACCEL PIPELINE auto{__PIPE__L6}`: Use the automatic pipeline settings for this loop.
22. `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}`: Use the automatic tile settings for this loop.
23. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}`: Use the automatic parallel settings for this loop.
24. `#pragma ACCEL PIPELINE auto{__PIPE__L7}`: Use the automatic pipeline settings for this loop.
25. `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}`: Use the automatic tile settings for this loop.
26. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}`: Use the automatic parallel settings for this loop.
27. `#pragma ACCEL PIPELINE auto{__PIPE__L8}`: Use the automatic pipeline settings for this loop.
28. `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}`: Use the automatic tile settings for this loop.
29. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}`: Use the automatic parallel settings for this loop.
30. `#pragma ACCEL PIPELINE auto{__PIPE__L9}`: Use the automatic pipeline settings for this loop.
31. `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}`: Use the automatic tile settings for this loop.
32. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}`: Use the automatic parallel settings for this loop.
33. `#pragma ACCEL PIPELINE auto{__PIPE__L10}`: Use the automatic pipeline settings for this loop.
34. `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}`: Use the automatic tile settings for this loop.
35. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}`: Use the automatic parallel settings for this loop.
36. `#pragma ACCEL PIPELINE auto{__PIPE__L11}`: Use the automatic pipeline settings for this loop.
37. `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}`: Use the automatic tile settings for this loop.
38. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}`: Use the automatic parallel settings for this loop.
39. `#pragma ACCEL PIPELINE auto{__PIPE__L12}`: Use the automatic pipeline settings for this loop.
40. `#pragma ACCEL TILE FACTOR=auto{__TILE__L12}`: Use the automatic tile settings for this loop.
41. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}`: Use the automatic parallel settings for this loop.
42. `#pragma ACCEL PIPELINE auto{__PIPE__L13}`: Use the automatic pipeline settings for this loop.
43. `#pragma ACCEL TILE FACTOR=auto{__TILE__L13}`: Use the automatic tile settings for this loop.
44. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}`: Use the automatic parallel settings for this loop.
45. `#pragma ACCEL PIPELINE auto{__PIPE__L14}`: Use the automatic pipeline settings for this loop.
46. `#pragma ACCEL TILE FACTOR=auto{__TILE__L14}`: Use the automatic tile settings for this loop.
47. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}`: Use the automatic parallel settings for this loop.
48. `#pragma ACCEL PIPELINE auto{__PIPE__L15}`: Use the automatic pipeline settings for this loop.
49. `#pragma ACCEL TILE FACTOR=auto{__TILE__L15}`: Use the automatic tile settings for this loop.
50. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}`: Use the automatic parallel settings for this loop.
51. `#pragma ACCEL PIPELINE auto{__PIPE__L16}`: Use the automatic pipeline settings for this loop.
52. `#pragma ACCEL TILE FACTOR=auto{__TILE__L16}`: Use the automatic tile settings for this loop.
53. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L16}`: Use the automatic parallel settings for this loop.
54. `#pragma ACCEL PIPELINE auto{__PIPE__L17}`: Use the automatic pipeline settings for this loop.
55. `#pragma ACCEL TILE FACTOR=auto{__TILE__L17}`: Use the automatic tile settings for this loop.
56. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L17}`: Use the automatic parallel settings for this loop.
57. `#pragma ACCEL PIPELINE auto{__PIPE__L18}`: Use the automatic pipeline settings for this loop.
58. `#pragma ACCEL TILE FACTOR=auto{__TILE__L18}`: Use the automatic tile settings for this loop.
59. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L18}`: Use the automatic parallel settings for this loop.
60. `#pragma ACCEL PIPELINE auto{__PIPE__L19}`: Use the automatic pipeline settings for this loop.
61. `#pragma ACCEL TILE FACTOR=auto{__TILE__L19}`: Use the automatic tile settings for this loop.
62. `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L19}`: Use the automatic parallel settings for this loop.