- `#pragma ACCEL PARALLEL FACTOR=auto{8}`: Execute loop iterations in parallel with a parallel factor of 8.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations in parallel with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{8}`: Execute loop iterations in parallel with a parallel factor of 8.
- `#pragma ACCEL PIPELINE auto{off}`: Do not pipeline the loop.
- `#pragma ACCEL TILE FACTOR=auto{1}`: Do not partition the loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{1}`: Execute loop iterations sequentially with a parallel factor of 1.
- `#pragma ACCEL PIPE