- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L4}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L4}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L4}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L5}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L5}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L5}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L6}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L6}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L6}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L7}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L7}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L7}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L8}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L8}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L8}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L9}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L9}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L9}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L10}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L10}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L10}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L11}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L11}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L11}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L12}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L12}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L12}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L13}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L13}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L13}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L14}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L14}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L14}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L15}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L15}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L15}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L16}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L16}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L16}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L17}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L17}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L17}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L18}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L18}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L18}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L19}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L19}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L19}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L20}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L20}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L20}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L21}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L21}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L21}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L22}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L22}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L22}`: Automatically assign a tile to this loop.
- `#pragma ACCEL PARALLEL FACTOR=auto{__PARA__L23}`: Automatically assign a parallel factor to this loop.
- `#pragma ACCEL PIPELINE auto{__PIPE__L23}`: Automatically assign a pipeline to this loop.
- `#pragma ACCEL TILE FACTOR=auto{__TILE__L23}`: Automatically assign a tile to this loop.